apiVersion: apps/v1
kind: Deployment
metadata:
  name: apistone1
spec:
  selector:
    matchLabels:
      app: apistone1
  template:
    metadata:
      labels:
        app: apistone1
    spec:
      containers:
      - name: apistone1
        image: team1project
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: apistone1-sevice
spec:
  selector:
    app: apistone1
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80

